### PR TITLE
fix: clean up atomone references in x/dynamicfee

### LINKED ISSUE #91: x/dynamicfee: amino name and README still reference atomone/atomoned
Now that `x/dynamicfee` lives in this SDK fork, a few leftovers from its
AtomOne origin should be cleaned up for consistency.

### 1. Amino name is out of line with every other module

`x/dynamicfee/types/codec.go`:

```go
legacy.RegisterAminoMsg(cdc, &MsgUpdateParams{}, "atomone/x/dynamicfee/v1/MsgUpdateParams")
```

Every sibling module in this fork follows `cosmos-sdk/x/<module>/MsgUpdateParams`:

| Module | Amino name |
|---|---|
| bank | `cosmos-sdk/x/bank/MsgUpdateParams` |
| auth | `cosmos-sdk/x/auth/MsgUpdateParams` |
| mint | `cosmos-sdk/x/mint/MsgUpdateParams` |
| consensus | `cosmos-sdk/x/consensus/MsgUpdateParams` |
| slashing | `cosmos-sdk/x/slashing/MsgUpdateParams` |
| staking | `cosmos-sdk/x/staking/MsgUpdateParams` |

Proposal: rename to `cosmos-sdk/x/dynamicfee/MsgUpdateParams`.

Impact is low in practice — `MsgUpdateParams` is only sent as a payload of
`MsgSubmitProposal` and is forged by the chain binary itself, so sign-doc
construction and verification move in lockstep. The rename should land in the
same chain upgrade as the proto package move (`atomone.dynamicfee.v1` →
`cosmos.dynamicfee.v1`) so there is only one discontinuity.

### 2. README still says `atomoned`

`x/dynamicfee/README.md` documents CLI examples using `atomoned`:

- line 367, 375, 381, 404, 410, 428, 434, 449, 455

Since this module now ships inside the SDK and can be consumed by any chain,
the binary name should be generic (e.g. `simd`, matching the rest of the SDK
docs) or a placeholder like `<appd>`.

### 3. README gRPC paths still use `atomone.dynamicfee.v1`

`x/dynamicfee/README.md` lines 473, 481, 508, 516, 539, 548, 568, 576:

```
atomone.dynamicfee.v1.Query/Params
atomone.dynamicfee.v1.Query/State
atomone.dynamicfee.v1.Query/GasPrice
atomone.dynamicfee.v1.Query/GasPrices
```

The proto package is now `cosmos.dynamicfee.v1`, so these should be
`cosmos.dynamicfee.v1.Query/*`. Same for the `uatone` example denom — either
generalise to `stake` / `<denom>` or keep but note it's an example from the
consumer chain.

### PR DESCRIPTION
**Pull request by tbruyelle**
- Rename amino msg name from atomone/x/dynamicfee/v1 to cosmos-sdk/x/dynamicfee
- Replace atomoned binary with simd in CLI examples
- Update gRPC paths from atomone.dynamicfee.v1 to cosmos.dynamicfee.v1
- Add autocli config to skip UpdateParams (authority gated)

Closes #91

### CODE REVIEW

File: x/dynamicfee/autocli.go [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+			Service: dynamicfeev1.Msg_serviceDesc.ServiceName,
+			RpcCommandOptions: []*autocliv1.RpcCommandOptions{
+				{
+					RpcMethod: "UpdateParams",
+					Skip:      true, // skipped because authority gated
+				},
+			},
+		},
+	}
+}
```
Comment (giunatale) [inline x/dynamicfee/autocli.go]:
```suggestion
}

```

**Review by giunatale — APPROVED** [review]
TY!
