### PR TITLE
fix(x/gov): prevent governance re-delegation right after creating a new governance delegation.

### LINKED ISSUE #64: [Bug]: UpdateGovernorStatus does not create a self-governance delegation.
Governor Status can be Active Inactive or Unspecified ([gov.proto:444](https://github.com/atomone-hub/cosmos-sdk/blob/release/v0.50.x/proto/cosmos/gov/v1/gov.proto#L444)) .

[UpdateGovernorStatus](https://github.com/atomone-hub/cosmos-sdk/blob/release/v0.50.x/x/gov/keeper/msg_server.go#L449) is used to change the status of a governor Active->Inactive, Inactive->Active.
However, the transition Inactive->Active can only happen if the governor has the minimum self-delegation required to be a governor.

In the case in which the update is Inactive->Active, UpdateGovernorStatus first checks if the governor has the required GOVERNANCE minimum self delegation, and return error if this is not the case (this is done by calling [ValidateGovernorMinSelfDelegation at line 486](https://github.com/atomone-hub/cosmos-sdk/blob/release/v0.50.x/x/gov/keeper/msg_server.go#L486))

Then, sets the governor as active (if the tx is Inactive->Active), and handle the case in which the governance self-delegation did not exist (`if` at line [503](https://github.com/atomone-hub/cosmos-sdk/blob/release/v0.50.x/x/gov/keeper/msg_server.go#L503)). However, if the governance self delegation did not exist already, the function would have returned at [line 487](https://github.com/atomone-hub/cosmos-sdk/blob/release/v0.50.x/x/gov/keeper/msg_server.go#L487). Therefore that `if` body ([lines 503-508](https://github.com/atomone-hub/cosmos-sdk/blob/release/v0.50.x/x/gov/keeper/msg_server.go#L504))  is dead code, it can never be reached.

At line 486 we probably want to check if the sum of all the delegations (NOT governance delegations) of the address that wants to be an active governor is higher than the minimum governance delegation. Basically, using the same flow already existing at lines [375-382](https://github.com/atomone-hub/cosmos-sdk/blob/release/v0.50.x/x/gov/keeper/msg_server.go#L375).

### PR DESCRIPTION
**Pull request by giuliostramondo**
The creation of a governance self-delegation could never happen in `UpdateGovernorStatus`, a call to [ValidateGovernorMinSelfDelegation](https://github.com/atomone-hub/cosmos-sdk/blob/release/v0.50.x/x/gov/keeper/msg_server.go#L486) would generate a panic if the governor did not already have a minimum governance self delegation (see #64).

This PR addresses issue #64, and resolves an issue that could cause a governance re-delegation to happen right after the creation of a self governance delegation. 

Fixes A-19
Closes: #64

### CODE REVIEW

**Review by tbruyelle — APPROVED** [review]
I've updated a bit the tests, other than that all good.

File: x/gov/keeper/msg_server_test.go [hunk 1]
```diff
@@ -1738,3 +1746,84 @@ func (suite *KeeperTestSuite) TestSubmitProposal_InitialDeposit() {
...
+			// to satisfy the GovernorStatusChangePeriod (default 28 days)
+			pastTime := time.Now().Add(-30 * 24 * time.Hour)
+			governor, err := v1.NewGovernor(govAddr.String(), v1.GovernorDescription{}, pastTime)
+			require.NoError(t, err)
+			governor.Status = v1.Inactive
+			governor.LastStatusChangeTime = &pastTime
+			err = govKeeper.Governors.Set(ctx, governor.GetAddress(), governor)
+			require.NoError(t, err)
+
+			_, err = msgSrvr.UpdateGovernorStatus(ctx, v1.NewMsgUpdateGovernorStatus(addr, v1.Active))
```
Comment (Pantani) [inline x/gov/keeper/msg_server_test.go:1827]: This test only covers the case where no governance delegation exists yet. The behavior change in `UpdateGovernorStatus` is [the else-if redelegation branch for an account that already delegates to another governor](https://github.com/atomone-hub/cosmos-sdk/pull/65/changes#diff-50a11739adeec5335e446d4444326785c040c57da2c65abe9b9713aec18183ffR513), but that state is never seeded here. Could we add a case that starts with an existing delegation to a different governor?

Comment (tbruyelle) [reply x/gov/keeper/msg_server_test.go:1827]: Good point @Pantani , I've updated the test with this particular case. See 39d367563ade345f33f50c2826eea769eaf99e60

**Review by Pantani — APPROVED** [review]
