### PR TITLE
feat: fixed commission rate and max rate parameter

### LINKED ISSUE #172: Add fixed chain-set commission for validators to Nakamoto Bonus
As per a comment in the Nakamoto Bonus [forum post](https://common.xyz/atomone/discussion/1277369-signaling-proposal-for-the-nakamoto-bonus)

> Such a model will work effectively only when all validators have the same generally defined commission

I tend to agree with it, but most importantly this was something we already had discussed/wanted and we kind of forgot to do.

I propose we add it to the Nakamoto Bonus ADR and implementation. Chain-set commission fixed to 5%.

### PR DESCRIPTION
**Pull request by Pantani**
close https://github.com/atomone-hub/atomone/issues/172

### CODE REVIEW

File: x/staking/keeper/msg_server.go [hunk 1]
```diff
@@ -184,8 +199,23 @@ func (k msgServer) EditValidator(ctx context.Context, msg *types.MsgEditValidato
...
+				return nil, errorsmod.Wrapf(types.ErrCommissionLTRateNotEqual, "if the validity minimum and maximum commission rates are equal (%s), the commission rate (%s) must be equal too", msg.CommissionRate.String(), minCommissionRate.String())
+			}
+		} else {
+			if msg.CommissionRate.LT(minCommissionRate) {
+				return nil, errorsmod.Wrapf(types.ErrCommissionLTMinRate, "commission rate (%s) cannot be less than the min commission rate %s", msg.CommissionRate.String(), minCommissionRate.String())
+			}
+
+			if msg.CommissionRate.GT(maxCommissionRate) {
+				return nil, errorsmod.Wrapf(types.ErrCommissionLTMaxRate, "cannot set validator (%s) commission to more than minimum rate of %s", msg.CommissionRate.String(), maxCommissionRate.String())
+			}
```
Comment (tbruyelle) [inline x/staking/keeper/msg_server.go]: Duplicated code.

Could also be simplified with a single condition, something like this:
```go
if msg.CommissionRate.LT(minCommissionRate) || msg.CommissionRate.GT(maxCommissionRate) {
	return nil, errorsmod.Wrapf(types.ErrCommissionOutOfBound,
		"commission rate (%s) must be between %s and %s",
		msg.CommissionRate.String(), minCommissionRate.String(), maxCommissionRate.String(),
	)
}
```

File: x/staking/simulation/genesis.go [hunk 2]
```diff
@@ -52,10 +59,12 @@ func RandomizedGenState(simState *module.SimulationState) {
 
 	simState.AppParams.GetOrGenerate(historicalEntries, &histEntries, simState.Rand, func(r *rand.Rand) { histEntries = getHistEntries(r) })
 
+	simState.AppParams.GetOrGenerate(maximumCommissionRate, &histEntries, simState.Rand, func(r *rand.Rand) { maxCommissionRate = getMaxCommissionRate(r) })
```
Comment (tbruyelle) [inline x/staking/simulation/genesis.go]: For some curious reason, `minCommissionRate` is not initialized here. Secondly I don't think you should pass the address og `histEntries` here.

File: x/staking/types/params.go [hunk 3]
```diff
@@ -19,30 +19,39 @@ const (
...
 	DefaultMaxEntries uint32 = 7
 
-	// DefaultHistorical entries is 10000. Apps that don't use IBC can ignore this
+	// DefaultHistoricalEntries default historical entries is 10000. Apps that don't use IBC can ignore this
 	// value by not adding the staking module to the application module manager's
 	// SetOrderBeginBlockers.
 	DefaultHistoricalEntries uint32 = 10000
+
+	// DefaultMaxCommission default maximum commission.
+	DefaultMaxCommission = 100 // 30% (30/100 = 0.3 = 30%
```
Comment (tbruyelle) [inline x/staking/types/params.go]: `// 30% (30/100 = 0.3 = 30%` 

This comment seems wrong.

**Review by tbruyelle — CHANGES_REQUESTED** [review]
Don't you need a store migration to initialize the max commission value ?

EDIT: sorry I was on a review rush and didn't realize this PR was marked as draft :grimacing:

File: x/staking/migrations/v3/json_test.go [hunk 4]
```diff
@@ -43,6 +43,7 @@ func TestMigrateJSON(t *testing.T) {
 	"params": {
 		"bond_denom": "stake",
 		"historical_entries": 10000,
+		"max_commission_rate": "1.000000000000000000",
```
Comment (Pantani) [inline x/staking/migrations/v3/json_test.go:46]:
```suggestion
```

File: x/staking/types/errors.go
Comment (julienrbrt) [inline x/staking/types/errors.go:1]: We should make sure to keep the same error code unchanged. If we need an extra error, let's add it below.
This would break **badly written** clients only reading the error code.

File: x/staking/types/params.go [hunk 5]
```diff
@@ -203,3 +210,48 @@ func validateMinCommissionRate(i interface{}) error {
...
+func validateCommissionRate(minimum, maximum interface{}) error {
+	if err := validateMinCommissionRate(minimum); err != nil {
+		return err
+	}
+
+	if err := validateMaxCommissionRate(maximum); err != nil {
+		return err
+	}
+
+	vMin, ok := minimum.(math.LegacyDec)
```
Comment (julienrbrt) [inline x/staking/types/params.go]: nit: we could have validateXXX return the already type casted value to avoid redoing it here.

File: x/staking/types/params_legacy.go
Comment (julienrbrt) [inline x/staking/types/params_legacy.go:1]: This should be reverted. Params are stored in the module, so this won't exist in x/params

**Review by julienrbrt — COMMENTED** [review]
lgtm! i just have some comments.

Should we have the fork be opinionated and put as default max value 5%? This would avoid needing adding this setting in the v4 migration handler.

File: x/staking/keeper/msg_server.go [hunk 6]
```diff
@@ -48,8 +47,22 @@ func (k msgServer) CreateValidator(ctx context.Context, msg *types.MsgCreateVali
...
-		return nil, errorsmod.Wrapf(types.ErrCommissionLTMinRate, "cannot set validator commission to less than minimum rate of %s", minCommRate)
+	maxCommRate, err := k.MaxCommissionRate(ctx)
+	if err != nil {
+		return nil, err
+	}
+
+	if maxCommRate.Equal(minCommRate) {
+		if !msg.Commission.Rate.Equal(minCommRate) {
+			return nil, errorsmod.Wrapf(types.ErrCommissionOutOfBound, "if the validity minimum and maximum commission rates are equal (%s), the commission rate (%s) must be equal too", minCommRate.String(), msg.Commission.Rate.String())
+		}
```
Comment (tbruyelle) [inline x/staking/keeper/msg_server.go]: Is this condition really necessary? It looks like the condition just below already fulfils the purpose.

File: x/staking/keeper/msg_server.go (hunk 1 above)
Comment (tbruyelle) [reply x/staking/keeper/msg_server.go]: @Pantani why this comment was marked as resolved ?

File: x/staking/types/params.go [hunk 7]
```diff
@@ -203,3 +210,48 @@ func validateMinCommissionRate(i interface{}) error {
...
+}
+
+func validateCommissionRate(minimum, maximum interface{}) error {
+	if err := validateMinCommissionRate(minimum); err != nil {
+		return err
+	}
+
+	if err := validateMaxCommissionRate(maximum); err != nil {
+		return err
+	}
```
Comment (tbruyelle) [inline x/staking/types/params.go:221]: Let's have a single `validateCommissionRate()` for both min and max, and then wrap any error to indicate if the related commision was min or max.

```go
if err := validateCommissionRate(minimum); err != nil {
		return fmt.Error("min commission: %w", err)
}
if err := validateCommissionRate(maximum); err != nil {
		return fmt.Error("max commission: %w", err)
}
```

File: x/staking/types/params.go (hunk 5 above)
Comment (tbruyelle) [reply x/staking/types/params.go]: Actually there is no reason to have `interface{}` parameters for this function at the first place. Let's change the params to `math.LegacyDec` and we're good.

Looking at the rest of file... Why the hell all the validate functions of this file use `interface{}` ??

**Review by tbruyelle — CHANGES_REQUESTED** [review]

**Comment by Pantani** [comment]
> lgtm! i just have some comments.
> 
> Should we have the fork be opinionated and put as default max value 5%? This would avoid needing adding this setting in the v4 migration handler.

Do you mean have a hardcoded value if the value is not in the store?

**Comment by Pantani** [comment]
@julienrbrt, something weird is happening with the integration tests, but it's hard to debug. Looks like the gas used is different in some method. Not being deterministic. Do you have any thoughts on it?

**Comment by julienrbrt** [comment]
> @julienrbrt, something weird is happening with the integration tests, but it's hard to debug. Looks like the gas used is different in some method. Not being deterministic. Do you have any thoughts on it?

Store access changed during execution. Meaning some queries got more expensive. If it is a static value you can just bump it in the test to make it pass.

**Comment by julienrbrt** [comment]
> > lgtm! i just have some comments.
> > 
> > Should we have the fork be opinionated and put as default max value 5%? This would avoid needing adding this setting in the v4 migration handler.
> 
> Do you mean have a hardcoded value if the value is not in the store?

I mean de DefaultMaxCommisionRate in the default params

File: x/staking/keeper/msg_server.go (hunk 1 above)
Comment (Pantani) [reply x/staking/keeper/msg_server.go]: sorry, I forgot to push the other changes

File: x/staking/types/params.go (hunk 5 above)
Comment (Pantani) [reply x/staking/types/params.go]: Sorry, I encountered an issue in the tests where the max commission rate was always null, so I added the legacy table to see if there was any reference in the tests. I will remove it now

**Comment by Pantani** [comment]
> > @julienrbrt, something weird is happening with the integration tests, but it's hard to debug. Looks like the gas used is different in some method. Not being deterministic. Do you have any thoughts on it?
> 
> Store access changed during execution. Meaning some queries got more expensive. If it is a static value you can just bump it in the test to make it pass.

ohhh, I found it. The error does not indicate the location of the error; we need to see it in the code. I thought it was automatically calculated, but it's a hardcoded value. Thanks, changed

**Comment by Pantani** [comment]
> > > lgtm! i just have some comments.
> > > Should we have the fork be opinionated and put as default max value 5%? This would avoid needing adding this setting in the v4 migration handler.
> > 
> > 
> > Do you mean have a hardcoded value if the value is not in the store?
> 
> I mean de DefaultMaxCommisionRate in the default params

I like the idea, wdyt @giunatale @tbruyelle @giuliostramondo ?

**Review by tbruyelle — APPROVED** [review]
LGTM 👍

**Comment by tbruyelle** [comment]
> > > > lgtm! i just have some comments.
> > > > Should we have the fork be opinionated and put as default max value 5%? This would avoid needing adding this setting in the v4 migration handler.
> > > 
> > > 
> > > Do you mean have a hardcoded value if the value is not in the store?
> > 
> > 
> > I mean de DefaultMaxCommisionRate in the default params
> 
> I like the idea, wdyt @giunatale @tbruyelle @giuliostramondo ?

Current min and max default commission are respectively 0 and 100%, that sounds good to me.
I don't think we should provide an opinionated fork with fixed 5% commission. AtomOne is tied by its constitution, unlike a chain that depends on the fork.

**Review by julienrbrt — DISMISSED** [review]

File: x/staking/module.go [hunk 8]
```diff
@@ -34,7 +34,7 @@ import (
 )
 
 const (
-	consensusVersion uint64 = 5
+	consensusVersion uint64 = 6
```
Comment (julienrbrt) [inline x/staking/module.go:37]: Good practice is to do a no-op migration for this.

Comment (Pantani) [reply x/staking/module.go:37]: Can you give me an example of how it works?

Comment (julienrbrt) [reply x/staking/module.go:37]: https://github.com/atomone-hub/cosmos-sdk/blob/release/v0.50.x/x/gov/module.go#L287-L289
except the migration function is a noop.

Comment (tbruyelle) [reply x/staking/module.go:37]: I don't understand why you talk about no-op migration. There is an op, which is to feed the max commission parameter :thinking:

Comment (julienrbrt) [reply x/staking/module.go:37]: Indeed! Then the migration must be wired.

**Comment by Pantani** [comment]
@julienrbrt done!! migrations wired

File: x/staking/module.go (hunk 8 above)
Comment (Pantani) [reply x/staking/module.go:37]: [050626e](https://github.com/atomone-hub/cosmos-sdk/pull/19/commits/050626e6805fc36d249bbcb59e6f0f76b3f87fc0)

Comment (tbruyelle) [reply x/staking/module.go:37]: ahah all good then!

**Review by julienrbrt — APPROVED** [review]

**Review by giunatale — CHANGES_REQUESTED** [review]
can we extend the `x/staking/README.md` to also include explicitly the fact that commission is now managed by chain parameters? I would like the docs to be updated more consistently

**Comment by Pantani** [comment]
> can we extend the `x/staking/README.md` to also include explicitly the fact that commission is now managed by chain parameters? I would like the docs to be updated more consistently

done on [a6e4ab4](https://github.com/atomone-hub/cosmos-sdk/pull/19/commits/a6e4ab48abfc1320043aba43dc28e7f639a6444a)

**Review by giunatale — APPROVED** [review]
